name: Build & Deploy to EC2 (Docker)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Build & Push Docker Image ---
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/deploy-backend-to-ec2:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/deploy-backend-to-ec2:latest

      # --- Deploy to EC2 ---
      - name: Deploy Docker Container on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # now ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/deploy-backend-to-ec2:latest
            docker stop deploy-backend-to-ec2 || true
            docker rm deploy-backend-to-ec2 || true
            docker run -d --env-file /home/ubuntu/app/.env -p 3000:3000 --name backend ghcr.io/${{ github.repository_owner }}/deploy-backend-to-ec2:latest
